export const ACTIONS = {
  START_GAME: 'START_GAME',
  FINISH_GAME: 'FINISH_GAME',
  GO_TO_LOBBY: 'LOBBY',

  SET_LIST: 'SET_LIST',
  SET_LIST_STATE: 'SET_LIST_STATE',
  REMOVE_BLOCK_FROM_LIST: 'REMOVE_BLOCK_FROM_LIST',
  ADD_BLOCK_TO_LIST: 'ADD_BLOCK_TO_LIST',

  SET_FIELD_STATE: 'SET_FIELD_STATE',
  REMOVE_BLOCK_FROM_FIELD: 'REMOVE_BLOCK_FROM_FIELD',
  ADD_BLOCK_TO_FIELD: 'ADD_BLOCK_TO_FIELD',

  CLEAR_EVENT: 'CLEAR_EVENT',
  FIELD_EVENT: 'FIELD_EVENT',
  LIST_EVENT: 'LIST_EVENT',
  TASK_EVENT: 'TASK_EVENT',
  FINISH_EVENT: 'FINISH_EVENT',

  NEXT_TASK: 'NEXT_TASK',
  SET_TASK: 'SET_TASK',
  SET_PLAYERS: 'SET_PLAYERS',
  ADD_PLAYER: 'ADD_PLAYER',
  REMOVE_PLAYER: 'REMOVE_PLAYER',

  SET_HOST: 'SET_HOST',
  REMOVE_HOST: 'REMOVE_HOST',

  MOVE_REQUEST: 'MOVE_REQUEST',
  LOCK_REQUEST: 'LOCK_REQUEST',
  LOCK_REQUEST_OPEN_ALL: 'LOCK_REQUEST_OPEN_ALL',
  LOCK_EVENT: 'LOCK_EVENT',
};
